tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "wix/brew"

cask_args appdir: "/Applications"

brew "ack"
brew "applesimutils"
brew "binutils"
brew "ccat"
brew "chruby"
brew "cocoapods"
brew "coreutils"
brew "diffutils"
brew "direnv"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gawk"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "gnupg"
brew "grep"
brew "gzip"
brew "jq"
brew "jupyterlab"
brew "moreutils"
brew "neovim"
brew "node"
brew "python"
brew "pyenv"
brew "rename"
brew "rsync"
brew "ruby-install"
brew "rust"
brew "screen"
brew "starship"
brew "stow"
brew "swiftlint"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "zlib"
brew "zplug"
brew "zsh"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

cask "airpass"
cask "alacritty"
cask "alfred"
cask "dozer"
cask "flux"
cask "font-hack"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "kap"
cask "lulu"
cask "postman"
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"

# install gradle here, since by now the jdk is installed
# brew "gradle"
