tap "hashicorp/tap"
tap "koekeishiya/formulae"
# tap "wix/brew"

cask_args appdir: "/Applications"

brew "ack"

brew "awscli"
brew "binutils"
brew "ccat"
brew "chruby"
# brew "cocoapods"
brew "coreutils"
brew "diffutils"
brew "direnv"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gawk"
brew "git"
brew "git-filter-repo"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "gnupg"
brew "gpg2"
brew "grep"
brew "gzip"
brew "jq"
brew "jupyterlab"
brew "moreutils"
brew "nano"
brew "neovim"
brew "node"
brew "nvm"
brew "postgresql"
brew "python"
brew "pyenv"
brew "rename"
brew "rsync"
brew "ruby-install"
brew "rust"
brew "screen"
brew "starship"
brew "stow"
# brew "swiftlint"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "zlib"
brew "zplug"
brew "zsh"
# brew "koekeishiya/formulae/skhd"
# brew "koekeishiya/formulae/yabai"
brew "hashicorp/tap/terraform"

# cask "airpass"
# cask "boop"
cask "flux"
cask "font-hack"
cask "font-hack-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "iterm2"
cask "pgadmin4"
cask "postman"
# cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
